Json schema 2
trifork/cheetah-charts pull request #111
Opened 2023-09-12 07:39 UTC by iblutrifork

2023-09-26 15:50 UTC, AndersBennedsgaard requested changes
It would be nice to be able to remove many/all of the `fail` and `required` fields in https://github.com/trifork/cheetah-charts/blob/main/charts/flink-job/templates/_helpers.tpl.
Such as https://github.com/trifork/cheetah-charts/blob/998e0953da1a893685a35c7a53f4e69a8582121b/charts/flink-job/templates/_helpers.tpl#L145 which says that `topics[*].name` is required, and https://github.com/trifork/cheetah-charts/blob/998e0953da1a893685a35c7a53f4e69a8582121b/charts/flink-job/templates/_helpers.tpl#L151 which says that `topics[*].type` must be `input` or `output`

2023-09-26 15:50 UTC, AndersBennedsgaard commented on charts/flink-job/values.schema.json
> +        },
```suggestion
        "args": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
```

2023-09-26 15:50 UTC, AndersBennedsgaard commented on charts/flink-job/values.schema.json
> +          "type": "string"
Must be either "running" or "suspended"

2023-09-26 15:50 UTC, AndersBennedsgaard commented on charts/flink-job/values.schema.json
> +          "required": ["enabled", "labels", "selectors", "targetPort"]
```suggestion
          "required": ["enabled", "targetPort"]
```

2023-09-26 15:50 UTC, AndersBennedsgaard commented on charts/flink-job/values.schema.json
> +      ]
```suggestion
      "required": [
        "automountServiceAccountToken",
        "create"
      ]
```

2023-09-26 15:50 UTC, AndersBennedsgaard commented on charts/flink-job/values.schema.json
> +            }
```suggestion
            "memory": {
              "oneOf": [
                {
                  "type": "string"
                },
                {
                  "type": "number"
                }
              ]
            },
            "cpu": {
              "oneOf": [
                {
                  "type": "string"
                },
                {
                  "type": "number"
                }
              ]
            }
```

2023-09-26 15:50 UTC, AndersBennedsgaard commented on charts/flink-job/values.schema.json
> +          "required": ["cpu", "memory"]
```suggestion
          }
```

2023-09-26 15:50 UTC, AndersBennedsgaard commented on charts/flink-job/values.schema.json
> +        },
Same as above.

2023-09-26 15:50 UTC, AndersBennedsgaard commented on charts/flink-job/values.schema.json
> +      ]
```suggestion
      "required": [
        "env",
        "envFrom",
        "podAnnotations",
        "podTemplate",
        "ports",
        "replicas",
        "resource",
        "volumeMounts",
        "volumes"
      ]
```

2023-10-03 11:46 UTC, iblutrifork commented on charts/flink-job/values.schema.json
> +    },
Yup, I'll use an enum here

2023-10-11 06:38 UTC, AndersBennedsgaard reviewed
Small change, but otherwise LGTM :smile:

2023-10-17 12:38 UTC, AndersBennedsgaard approved these changes

2023-10-17 13:19 UTC, merged