Improve HA config, and json validation
trifork/cheetah-charts pull request #211
Opened 2024-04-16 12:58 UTC by pegtrifork

2024-04-16 13:08 UTC, rkthtrifork commented on charts/flink-job/values.schema.json
> +                  "high-availability.storageDir"
```suggestion
```

2024-04-16 13:15 UTC, rkthtrifork commented on charts/flink-job/values.schema.json
> +                  "high-availability.storageDir"
```suggestion
```

2024-04-16 13:19 UTC, rkthtrifork requested changes
i dont understand why exclusiveMinimum means we need the storage section

2024-04-17 06:57 UTC, pegtrifork commented
> i dont understand why exclusiveMinimum means we need the storage section

2024-04-17 07:05 UTC, pegtrifork commented
> i dont understand why exclusiveMinimum means we need the storage section

It the best way I could find to check for a non empty string. We cannot use "required" since the storage section is already present in values.yaml with an empty string to be able to generate helm docs

2024-04-17 12:36 UTC, merged