Redpanda console
trifork/cheetah-charts pull request #216
Opened 2024-04-25 15:20 UTC by KastTrifork

2024-04-25 15:36 UTC, KastTrifork commented
I'm struggling with this again error: couldn't find key client-Id in Secret redpanda-console-test/redpanda-oauth2-proxy.
I have checked secrets in k9s and the client-id are stored in redpanda-oauth2-proxy

2024-05-01 07:40 UTC, KastTrifork commented
It works now, running on our cluster

2024-05-08 07:19 UTC, pegtrifork commented on charts/cheetah-redpanda-console/templates/service.yaml
> +    - port: 4180
To reverting this file to the default from redpanda-console. And only set default values in "values.yaml" instead

2024-05-08 07:19 UTC, pegtrifork commented on charts/cheetah-redpanda-console/templates/ingress.yaml
To reverting this file to the default from redpanda-console. And only set default values in "values.yaml" instead

2024-05-08 07:19 UTC, pegtrifork commented on charts/cheetah-redpanda-console/templates/deployment.yaml
> +            - containerPort: 4180
Should preferably also be taken from values, and should just match https://github.com/trifork/cheetah-charts/pull/216/files#diff-7f4165ef21ea4ac14fc7bc4e70899250ef7adeddae686abe79631a21aaa40e8eR29

2024-05-08 14:18 UTC, rkthtrifork commented on charts/cheetah-redpanda-console/values.schema.json
> +{
add these values

```yaml
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.5.1
          imagePullPolicy: IfNotPresent
          args:
            - --oidc-issuer-url={{.Values.oauth2Proxy.issuerUrl}}
            - --upstream=http://127.0.0.1:8080
            - --reverse-proxy=true
            - --email-domain={{.Values.oauth2Proxy.emailDomain}}
            - --cookie-secure=true
            - --cookie-name={{.Values.oauth2Proxy.cookieName}}
            - --provider=oidc
            - --http-address=0.0.0.0:{{.Values.service.port}}
            - --exclude-logging-path="/ping"
          readinessProbe:
            httpGet:
              path: /ping
              port: http-proxy
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /ping
              port: http-proxy
            initialDelaySeconds: 5
            periodSeconds: 5
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
              name: http-proxy
          env:
        {{- with .Values.oauth2Proxy.env }}
        {{- toYaml . | nindent 12 }}
```

2024-05-08 14:20 UTC, rkthtrifork requested changes
see comments and consider adding istio VirtualService for ingress

2024-05-08 14:46 UTC, rkthtrifork commented on charts/cheetah-redpanda-console/templates/NOTES.txt
> +This is helm chart is an extension of the console chart from the official helm chart repository.
```suggestion
This helm chart is an extension of the console chart from the official helm chart repository.
```

2024-05-08 14:46 UTC, rkthtrifork requested changes
typo

2024-05-08 14:53 UTC, merged