New Flink job chart
trifork/cheetah-charts pull request #68
Opened 2023-06-03 14:48 UTC by AndersBennedsgaard

Instead of trying to fix the existing Flink chart, we have elected to create a new, and deprecate the old "cheetah-flink-native" chart.
Meanwhile, we will make the values spec closer to the Kubernetes resources, such as the `FlinkDeployment` resource.

New chart requirements:

- [x] Rename to "flink-job"
- [x] Remove assumptions to how secrets are injected
- [x] Remove assumptions on the ingress controller
- [x] Remove kubernetes-replicator dependency
- [x] Figure out which configuration in `podTemplate` is overwritten by `xxxManager.podTemplate`
- [x] Smart configuration of Flink configuration
  - [x] Metrics
  - [x] Savepointing/checkpointing
  - [x] HA
- [x] Better documentation

2023-06-08 05:59 UTC, cthtrifork requested changes
Documentation looks good and easy to read. I still have mixed feelings on naming - it is not clear that they are not using their own chart, the official chart or their own chart, as the `cheetah`name has been removed. 
But if there has been a small group discussion and this has been voted, lets go for it.

We are missing the `flink.job.topics` values used in `cheetah-flink-native` - as we need to set the values both as an environment variable and as job arguements. The env values are used for data-discovery in backstage.

2023-06-09 10:36 UTC, pegtrifork requested changes

2023-06-09 10:36 UTC, pegtrifork commented on charts/flink-job/values.yaml
> +version: v1_15
```suggestion
version: v1_16
```
I think we should default to 1.16 since this is the version all of our jobs are running currently

2023-06-12 08:06 UTC, cthtrifork approved these changes

2023-06-12 08:46 UTC, pegtrifork approved these changes

2023-06-12 09:45 UTC, merged